default_language_version:
    python: python3.11

repos:
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.4.4
      hooks:
        - id: ruff
        - id: ruff-format
          args: [--config=ruff.toml, --diff]

    - repo: https://github.com/pycqa/isort
      rev: 5.13.2
      hooks:
        - id: isort
          name: isort (python)
          args: [--check]

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
        - id: detect-private-key
        - id: mixed-line-ending
          args: [ --fix=lf ]
        - id: check-added-large-files
          args: [ --maxkb=500 ]
        - id: check-ast
        - id: check-builtin-literals
        - id: check-case-conflict
        - id: check-docstring-first
        - id: check-merge-conflict
        - id: check-symlinks
        - id: debug-statements
        - id: end-of-file-fixer
        - id: debug-statements
        - id: requirements-txt-fixer
        - id: trailing-whitespace
        - id: check-toml
        - id: check-json
        - id: check-yaml
          args:
            - --allow-multiple-documents
